name: Release

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      scope:
        description: What to publish
        type: choice
        required: true
        default: Release
        options:
          - Release
          - Release Candidate
      bump:
        description: Semver component to increment
        type: choice
        required: true
        default: patch
        options:
          - patch
          - minor
          - major

permissions:
  contents: read

jobs:
  snapshot:
    name: Validate release
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: NerdsWhoFish/quill@v1
        with:
          dry-run: "true"
          publish: goreleaser

  release:
    name: Publish release
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: NerdsWhoFish/quill@v1
        with:
          bump: ${{ inputs.bump }}
          scope: ${{ inputs.scope }}
          publish: goreleaser
